apiVersion: apps/v1
kind: Deployment
metadata:
  name: busyboxnodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command:
        - sleep
        - "3600"
