apiVersion: apps/v1
kind: Deployment
metadata:
  name: busyboxnodeapp_new
spec:
  replicas: 10
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox-container
        image: busybox
        command:
        - sleep
        - "7200"
